### ISSUE TITLE
怎么没办法运行啊

### ISSUE THREAD

**Issue by semiconlon** [Tachone/Tachftp#1]
我是使用ftp作为客户端的，但是好像连接不上去，显示错误如下
`$ ftp 0.0.0.0 21       
ftp: connect: Connection refused
ftp> 
`

**Comment by Tachone** [comment]
默认配置文件miniftpd.conf中的listen_port=5188（测试的时候防止和vsftpd冲突），并非21端口。
所以你可以修改配置文件为21端口，也可以使用ftp 127.0.0.1 5188 登陆。
