### ISSUE TITLE
登录Ftpserver

### ISSUE THREAD

**Issue by MakingL** [Tachone/Tachftp#3]
您好：
请问怎么添加用户名和密码？默认的用户名和密码是多少？我在云服务器上运行了 FTP server 的代码，用FTP  工具请求时被拒绝连接，我的防火墙端口是正常打开的，用代码在服务器上请求连接是能够正常连接的，请问FTP 工具不能请求是什么原因呢？

**Comment by Tachone** [comment]
系统用户登录，/etc/passwd

**Comment by MakingL** [comment]
已解决，谢谢

**Comment by gczhcm** [comment]
@MakingL 请问是如何解决的？

**Comment by MakingL** [comment]
@gczhcm 就是登录的用户名应该是操作系统上的用户名，我当时是单独创建了个用户用于 ftp。其实这个这个项目忽略了个问题，就是防火墙的问题，被动模式下监听的端口应该保证防火墙是打开的。我当时自己加了一个小功能，被动模式下，只监听指定的端口号。有机会再 pull 进来

**Comment by gczhcm** [comment]
@MakingL 请问有源码可以分享一下吗

**Comment by MakingL** [comment]
@gczhcm 不好意思，刚才确认了一下，发现当时我不是根据这个 project 改的。不过跟这个project的很像。https://github.com/MakingL/ftpServer
